language: perl
perl:
  - "5.16"
language: "node_js"
node_js:
  - "0.10"
  - "0.11"
before_script:
  - npm install -g grunt-cli
  - npm install -g forever
  - mkdir ~/perl5
  - curl -L -O http://xrl.us/cpanm
  - perl cpanm App::cpanminus
  - export PERL_CPANM_OPT="--local-lib=~/perl5"
  - export PATH=$HOME/perl5/bin:$PATH;
  - export PERL5LIB=$HOME/perl5/lib/perl5:$PERL5LIB;
  - cpanm --installdeps --notest .
